### ISSUE TITLE
Une version Linux

### ISSUE THREAD

**Issue by Mouradif** [shadow2560/Ultimate-Switch-Hack-Script#1]
Salut,

Merci pour ton initiative de rendre le processus de root une switch plus simple. Ce serait cool d'avoir une version linux avec fuseelauncher.

**Comment by shadow2560** [comment]
Salut,
Une version Linux du projet devrait être un projet totalement à part car il faudrait réécrire totalement les scripts avec des contrôles d'erreurs différents et je ne pense pas que je le ferai vu le temps que cela prendrait à faire, déjà maintenir ce projet me prend du temps.
