### ISSUE TITLE
vbs path incorrect for nsZip.bat

### ISSUE THREAD

**Issue by Ancel1** [shadow2560/Ultimate-Switch-Hack-Script#2]
line 17

%windir%\system32\wscript.exe //Nologo ..\tools\Storage\functions\open_file.vbs "" "Fichier de jeu Switch (*.xci;*.nsp;*.xciz;*.nspz)|*.xci|*.nsp|*.xciz|*.nspz|"

**Comment by shadow2560** [comment]
Thanks, fixed in 2.10.61.
