### ISSUE TITLE
Support for SX Core / SX Lite flashed with Spacecraft-NX

### ISSUE THREAD

**Issue by rablatbenjamin** [shadow2560/Ultimate-Switch-Hack-Script#2]
When creating an SD Card for a Mariko Switch equipped with SX Core, the script integrates SX Gear because it assumes (i believe) that the SX chip is flashed with the SX Firmware. But I recently flashed my SX Core with Spacecraft-NX second release. 
Will the scrypt work properly for this configuration ?

Lors de la création d'une carte SD pour une Switch Mariko équipé d'un SX Core, le script intègre SX Gear car il suppose (j'imagine) que la puce SX est flashée avec le Firmware d'origine TX. Mais j'ai récemment flashé mon SX Core avec la deuxième version de Spacecraft-NX.
Est-ce que le scrypt fonctionne correctement pour cette configuration ?

**Comment by shadow2560** [comment]
Yes, it will work, the script copy effectively the SX Gear file but it also copy the "payload.bin" file (Hekate) witch is used by Spacecraft.

Oui, cela fonctionnera, le script copie effectivement les fichiers du SX Gear mais il copie aussi le fichier "payload.bin" (Hekate) qui est utilisé par Spacecraft
