### ISSUE TITLE
petite erreur dans homebrews.list

### ISSUE THREAD

**Issue by boucz** [shadow2560/Ultimate-Switch-Hack-Script#3]
bonjour,
à chaque fois que je lance le menu 4 pour préparer une carte sd, j'ai une erreur sur le téléchargement de ProdInfoInstaller.
Dans le fichier de profile \tools\default_configs\mixed_profile_all.ini, il est fait mention de ProdInfoEnabler (qui est le nom correct) alors que dans \tools\default_configs\Lists\homebrews.list, il est fait mention de ProdInfoInstaller (qui est une coquille).
Du coup, le script boucle sur une erreur de téléchargement de ProdInfoInstaller.
En corrigeant le fichier homebrews.list, (remplacement de ProdInfoInstaller par ProdInfoEnabler), la préparation de la carte SD se fait correctement.
Merci beaucoup pour ton travail, ce script est juste génial !!!

**Comment by shadow2560** [comment]
Bonjour,

Merci de m'avoir indiqué cette erreur, ceci est corrigé avec la version 4.1.5.
