### ISSUE TITLE
Exception: list index out of range ?

### ISSUE THREAD

**Issue by AntoineLannareix** [shadow2560/Ultimate-Switch-Hack-Script#4]
Bonjour,
j'ai un problème lorsque j’exécute NSC_Builder pour convertir un fichier NSP en XCI :

Processing: C:\Users\xxx\Bureau\Ultimate-Switch-Hack-Script-master\tools\NSC_Builder\Super Meat Boy\Super Meat Boy.nsp
Exception: list index out of range
Terminé

**Comment by shadow2560** [comment]
Salut,

Désolé mais les problèmes avec NSC_Builder ne me concerne pas, c'est à voir avec le créateur de celui-ci car moi je ne fais que la traduction.

Ceci dit quelques pistes, est-ce que tu as toutes les clés dans le fichier de clés (ne me donne pas ton fichier de clés par contre, juste précises-moi jusqu'à quelle Master_key ton fichier va)? Essaies aussi de placer le dossier de mon script ailleurs sur ton PC car le chemin jusqu'au bureau est long, place plutôt mon script à la racine du disque "C" par exemple histoire d'éviter d'avoir des chemins hyper long et aussi il n'est pas nécessaire de placer ton jeu dans le dossier de NSC_Builder.

**Comment by AntoineLannareix** [comment]
Salut,

Concernant le chemin d’accès trop long, j'ai mis sur le "C:", j'ai la même erreur, même en déplaçant le répertoire de jeu (contenant les NSP) = Pour moi, cela ne vient pas de là.

Après, voici la liste de ce que j'ai dans mon keys.txt (**sans dévoiler les clés**) :

- aes_kek_generation_source
aes_key_generation_source
bis_kek_source
bis_key_00
bis_key_01
bis_key_02
bis_key_03
bis_key_source_00
bis_key_source_01
bis_key_source_02
device_key
device_key_4x
keyblob_key_00
keyblob_key_01
keyblob_key_02
keyblob_key_03
keyblob_key_04
keyblob_key_05
keyblob_key_source_00
keyblob_key_source_01
keyblob_key_source_02
keyblob_key_source_03
keyblob_key_source_04
keyblob_key_source_05
keyblob_mac_key_00
keyblob_mac_key_01
keyblob_mac_key_02
keyblob_mac_key_03
keyblob_mac_key_04
keyblob_mac_key_05
keyblob_mac_key_source
master_kek_source_06
master_kek_source_07
master_kek_source_08
master_kek_source_09
master_kek_source_0a
master_key_source
package2_key_source
per_console_key_source
retail_specific_aes_key_source
rsa_oaep_kek_generation_source
rsa_private_kek_generation_source
secure_boot_key
titlekek_source
tsec_key
bis_key_00
bis_key_01
bis_key_02
bis_key_03
eticket_rsa_kek_source
eticket_rsa_kekek_source
header_kek_source
header_key
header_key_source
key_area_key_application_source
key_area_key_ocean_source
key_area_key_system_source
save_mac_kek_source
save_mac_key_source
sd_card_kek_source
sd_card_nca_key_source
sd_card_save_key_source
sd_seed
ssl_rsa_kek_source_x
ssl_rsa_kek_source_y

**Comment by shadow2560** [comment]
Il te manque beaucoup de clés, ton dump est à faire avec Lockpick-RCM et n'oublies pas de mettre aussi Sept que tu trouveras dans la release d'Atmosphere (si tu as préparé la SD avec mon script il sera déjà présent sur la SD).

PS: Il y a une fonction dans mon script (dans les "autres fonctionnalités" ou dans le menu des "fonctionnalités occasionnelles") qui permet de vérifier un fichier de clés, je suis certains qu'en le passant dedans il va te manquer un sacré paquet de clés.

PS2: Sinon faut essayer avec la version original de NSC_Builder, si la même erreur se produit alors cela signifie que ça ne viens pas de mon projet et donc je pourrais fermer cette issue, cependant je suis quasi certain maintenant que ça vient de ton fichier de clés.

**Comment by AntoineLannareix** [comment]
Ok je vais essayer, merci pour l'information.

**Comment by shadow2560** [comment]
N'oublies pas de faire un retour que je sache si je peux fermer le rapport de bug.

**Comment by AntoineLannareix** [comment]
> N'oublies pas de faire un retour que je sache si je peux fermer le rapport de bug.

Je regarderai ce week end :)

**Comment by AntoineLannareix** [comment]
Bonjour shadow2560, 
J'ai installé Lockpick_RCM.bin (dernière version) sur ma carte sd.
Concernant le fichier sept : je suis sous SX OS, je dois utilisé ton script pour préparer une nouvelle carte sd si j'ai bien compris ? pourquoi ne pas utiliser Lockpick_RCM à lancer depuis Payloads SX OS avec Sept sur la carte SD, cela reviens au même ?

**Comment by shadow2560** [comment]
Pour le dossier "sept" tu le récupères comme tu veux, soit en faisant une préparation de SD via mon script (pas besoin de supprimer quoi que se soit, ça prendra juste les nouveaux éventuels fichiers dans la copie) ou soit via la dernière release d'Atmosphere (juste pas besoin du fichier "payload.bin" qui s'y trouvera dans ce cas). Après pour lancer Lockpick-RCM tu fais bien comme tu veux, moi j'éviterais de passer par SX Loader parce que je sais que certains payloads posent problèmes s'ils sont lancés de cette façon.

**Comment by AntoineLannareix** [comment]
Ok je comprends, donc le profil 1 est le plus adapté pour mon cas (via ton programme de preparation de la SD) ?

**Comment by AntoineLannareix** [comment]
C'est bon j'ai choixi l'option 3 : pour SXOS, j'ai ensuite lancé le payload " Lockpick-RCM" depuis SX OS avec et fais un dump des clés, j'en ai au moins 151clés... je test maintenant la conversion nsp to XCI pour voir.

**Comment by AntoineLannareix** [comment]
J'ai pu convertir mes NSP en XCI !!! Merci c'est nickel !!
Dernière question : Puis-je partager ces fichiers XCI ainsi généré sans que quelqu'un ne retrouve mes "prod.keys" ?

**Comment by shadow2560** [comment]
Merci, je clôt cette issue qui, comme je le pensais bien depuis le début, n'avait rien à voir avec mon script.

Et pour ta dernière question désolé mais je ne répondrai pas, pas de support pour le warez ou partage de fichier de jeu ici, en plus encore une fois ça n'a rien à voir avec un problème lié à mon script.

Bonne continuation.
